// This file is auto-generated by @hotwired/stimulus-rails
import { application } from "./application"

// Eager load all controllers defined in the app/javascript/controllers directory
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)
